---

- name: Set hostname
  hostname: name={{inventory_hostname}}

- name: Update /etc/hosts for localhost
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost' owner=root group=root mode=0644

- name: Update /etc/hosts for hostname
  lineinfile: dest=/etc/hosts regexp='^127\.0\.1\.1' line='127.0.1.1 {{inventory_hostname}} {{inventory_hostname_short}}' owner=root group=root mode=0644
  
